In [1]:
# Versão da Linguagem Python

from platform import python_version
print('Versão de Python Neste Jupyter Notebook:', python_version())

Versão de Python Neste Jupyter Notebook: 3.10.5


In [2]:
import warnings
warnings.filterwarnings('ignore')

pip install numpy

### NumPy Arrays

In [3]:
import numpy as np

In [4]:
# Put volume in lacs
put_vol = [52.89, 45.14, 63.84, 77.1, 74.6]

In [5]:
# Call volume in lacs
call_vol = [49.51, 50.45, 59.11, 80.49, 65.11]

In [6]:
# Computing Put Call Ratio (PCR)
put_vol / call_vol

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [7]:
# Importing NumPy library
import numpy as np

In [8]:
# Creating arrays
n_put_vol = np.array(put_vol)

In [9]:
n_call_vol = np.array(call_vol)

In [10]:
n_put_vol

array([52.89, 45.14, 63.84, 77.1 , 74.6 ])

In [11]:
n_call_vol

array([49.51, 50.45, 59.11, 80.49, 65.11])

In [12]:
# Computing Put Call Ratio (PCR)
pcr = n_put_vol / n_call_vol

In [13]:
pcr

array([1.06826904, 0.89474727, 1.0800203 , 0.95788297, 1.14575334])

In [14]:
np.array([1, 'Python', True])

array(['1', 'Python', 'True'], dtype='<U11')

In [15]:
# Creating lists
list_1 = [1, 2, 3]

In [ ]:
# Adding two lists
list_1 + list_2

In [17]:
# Creating arrays
arr_1 = np.array([1, 2, 3])

In [18]:
arr_2 = np.array([5, 6, 4])

In [19]:
# Adding two arrays
arr_1 + arr_2

array([6, 8, 7])

#### N-dimensional arrays

In [20]:
# Checking array type
type(n_put_vol)

numpy.ndarray

In [21]:
# Recalling put and call volumes lists
put_vol

[52.89, 45.14, 63.84, 77.1, 74.6]

In [22]:
call_vol

[49.51, 50.45, 59.11, 80.49, 65.11]

In [23]:
# Creating a two-dimensional array
n_2d = np.array([put_vol, call_vol])

In [24]:
n_2d

array([[52.89, 45.14, 63.84, 77.1 , 74.6 ],
       [49.51, 50.45, 59.11, 80.49, 65.11]])

### Array creation using built-in functions

In [25]:
# zeros(shape, dtype=float) returns an array of a given shape and type, 
# filled with zeros. If the dtype is not provided as an input, 
# the default type for the array would be float.

In [26]:
# Creating a one-dimensional array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
# Creating a two-dimensional array
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
# Creating a one-dimensional array of integer type
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [29]:
# ones(shape, dtype=float) returns an array of a given shape and
# type, filled with ones. If the dtype is not provided as an input, the
# default type for the array would be float.

# Creating a one-dimensional array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
# Creating a one-dimensional array of integer type
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [31]:
# full(shape, fill_value, dtype=None) returns an array of a given
# shape and type, fill with fill_value given in input parameters.

# Creating a one-dimensional array with value as 12
np.full(5, 12)

array([12, 12, 12, 12, 12])

In [32]:
# Creating a two-dimensional array with value as 9
np.full((2, 3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [33]:
# arange([start, ]stop, [step]) returns an array with evenly
# spaced values within a given interval. Here the start and step parameters
# are optional. If they are provided NumPy will consider them
# while computing the output. Otherwise, range computation starts
# from 0. For all cases, stop value will be excluded in the output.

# Creating an array with only stop argument
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
# Creating an array with start and stop arguments
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [35]:
# Creating an array with given interval and step value
# as 0.5
np.arange(3, 8, 0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [36]:
# linspace(start, stop, num=50, endpoint=True) returns evenly
# spaced numbers over a specified interval. The number of samples
# to be returned is specified by the num parameter. The endpoint of the
# interval can optionally be excluded.

# Creating an evenly spaced array with five numbers within
# interval 2 to 3
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [37]:
# Creating an array excluding end value
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [38]:
# Creating an array with ten values within the specified
# interval

np.linspace(11, 20, num=10)

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

### Random Sampling in NumPy

In [39]:
# rand([d0, d1, ..., dn]) is used to create an array of a given shape
# and populate it with random samples from a uniform distribution over
# [0, 1). It takes only positive arguments. If no argument is provided,
# a single float value is returned.

# Generating single random number
np.random.rand()

0.41199410999908415

In [40]:
# Generating a one-dimensional array with four random
# values

np.random.rand(4)

array([0.31335106, 0.63092777, 0.98776663, 0.04225268])

In [41]:
# Generating a two-dimensional array
np.random.rand(2, 3)

array([[0.1176241 , 0.9314308 , 0.48498396],
       [0.8085828 , 0.47081334, 0.03785688]])

In [42]:
# randn([d0, d1, ..., dn]) is used to create an array of the given
# shape and populate it with random samples from a standard normal
# distributions. It takes only positive arguments and generates an array
# of shape (d0, d1, ..., dn) filled with random floats sampled
# from a univariate normal distribution of mean 0 and variance 1. If
# no argument is provided, a single float randomly sampled from the distribution is returned.

# Generating a random sample
np.random.randn()

0.528999298730004

In [43]:
# Generating a two-dimensional array over N(0, 1)
np.random.randn(2, 3)

array([[ 0.34647844, -0.89178325, -0.29181279],
       [ 1.99051379, -1.45282433,  1.00986342]])

In [44]:
# Generating a two-dimensional array over N(3, 2.25)
1.5 * np.random.randn(2, 3) + 3

array([[5.87007631, 2.73262119, 2.07521553],
       [3.1183391 , 4.59053087, 3.23107082]])

In [45]:
# randint(low, high=None, size=None) returns a random integer
# from a discrete uniform distribution with limits of low (inclusive) and
# high (exclusive). If high is None (the default), then results are from 0
# to low. If the size is specified, it returns an array of the specified size.

# Generating a random integer between 0 and 6
np.random.randint(6)

5

In [46]:
# Generating a random integer between 6 and 9
np.random.randint(6, 9)

6

In [47]:
# Generating a one-dimensional array with values between 3
# and 9

np.random.randint(3, 9, size=5)

array([7, 8, 7, 7, 3])

In [48]:
# Generating a two-dimensional array with values between 3
# and 9

np.random.randint(3, 9, size=(2, 5))

array([[8, 8, 6, 8, 8],
       [4, 7, 6, 3, 4]])

In [49]:
# random(size=None) returns a random float value between 0 and 1
# which is drawn from the continuous uniform distribution.

# Generating a random float
np.random.random()

0.24167422821201123

In [50]:
# Generating a one-dimensional array
np.random.random(3)

array([0.26924052, 0.51812704, 0.46919679])

In [51]:
# Generating a two-dimensional array
np.random.random((3, 2))

array([[0.20248503, 0.25434875],
       [0.25488729, 0.5643785 ],
       [0.02747401, 0.29545899]])

In [52]:
# binomial(n, p, size=None) returns samples drawn from a binomial
# distribution with n trials and p probability of success where n is
# greater than 0 and p is in the interval of 0 and 1.

# Number of trials, probability of each trial
n, p = 1, .5

In [53]:
# Flipping a coin 1 time for 50 times
samples = np.random.binomial(n, p, 50)

In [54]:
samples

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1])

In [55]:
# normal(mu=0.0, sigma=1.0, size=None) draws random samples
# from a normal (Gaussian) distribution. If no arguments provided, a
# sample will be drawn from N(0, 1).

# Initialize mu and sigma
mu, sigma = 0, 0.1

In [56]:
# Drawing 5 samples in a one-dimensional array
np.random.normal(mu, sigma, 5)

array([-0.03562153, -0.12902882, -0.02291848,  0.03427013,  0.03905115])

In [57]:
# shape (2, 5)
np.random.normal(mu, sigma, (2, 5))

array([[ 0.20767482, -0.05661352,  0.10890295,  0.17858038, -0.00071614],
       [ 0.03844385,  0.05115303, -0.03249614, -0.13410548,  0.1496267 ]])

In [58]:
# uniform(low=0.0, high=1.0, size=None) draws samples from a
# uniform distribution over the interval 0 (including) and 1 (excluding),
# if no arguments are provided. In other words, any value drawn is
# equally likely within the interval.
# Creating a one-dimensional array with samples drawn
# within [-1, 0)

np.random.uniform(-1, 0, 10)

array([-0.2831989 , -0.42593202, -0.35828446, -0.45908242, -0.58714516,
       -0.17238356, -0.61583388, -0.97999704, -0.44437585, -0.67081447])

In [59]:
# Creating a two-dimensional array with samples drawn
# within [0, 1)

np.random.uniform(size=(5, 2))

array([[0.95807866, 0.31595095],
       [0.26834006, 0.84540108],
       [0.39517406, 0.68325528],
       [0.70339975, 0.97197942],
       [0.81145384, 0.10772142]])

### Array Attributes and Methods

In [ ]:
# ndim attribute displays the number of dimensions of an array. Using
# this attribute on n_call_vol and pcr, we expect dimensions to be 1 and 2 respectively. Let’s check.
# Checking dimensions for n_call_vol array

np_call_vol.ndim

In [61]:
n_2d.ndim

2

In [62]:
# shape returns a tuple with the dimensions of the array. It may also
# be used to reshape the array in-place by assigning a tuple of array imensions to it.
# Checking the shape of the one-dimensional array

n_put_vol.shape

(5,)

In [63]:
# Checking shape of the two-dimensional array
n_2d.shape

(2, 5)

In [64]:
# Printing n_2d with 2 rows and 5 columns
n_2d

array([[52.89, 45.14, 63.84, 77.1 , 74.6 ],
       [49.51, 50.45, 59.11, 80.49, 65.11]])

In [65]:
# Reshaping n_2d using the shape attribute
n_2d.shape = (5, 2)

In [66]:
# Printing reshaped array
n_2d

array([[52.89, 45.14],
       [63.84, 77.1 ],
       [74.6 , 49.51],
       [50.45, 59.11],
       [80.49, 65.11]])

In [67]:
# size returns the number of elements in the array.
n_call_vol.size

5

In [68]:
n_2d.size

10

In [69]:
# dtype returns the data-type of the array’s elements. As we learned
# above, NumPy comes with its own data type just like regular built-in data types such as int, float, str, etc.

n_put_vol.dtype

dtype('float64')

In [70]:
# Creating a one-dimensional array with 1000 samples drawn
# from a normal distribution
samples = np.random.normal(5, 1.5, 1000)

In [71]:
# Creating a two-dimensional array with 25 samples
# drawn from a normal distribution

samples_2d = np.random.normal(5, 1.5, size=(5, 5))

In [72]:
samples_2d

array([[5.07379752, 4.36730802, 3.34475665, 4.56565369, 5.25763422],
       [5.41236199, 6.79706788, 5.62046383, 5.17967835, 4.80735688],
       [5.95932065, 4.71425406, 3.84824416, 6.38570291, 7.14757576],
       [6.31779307, 5.05359946, 5.53634242, 3.74420049, 5.24699917],
       [4.29446805, 6.264378  , 3.63557548, 6.03961456, 1.85255307]])

In [73]:
# mean(a, axis=None) returns the average of the array elements. The
# average is computed over the flattened array by default, otherwise
# over the specified axis.

In [74]:
# average(a, axis=None) returns the average of the array elements and works similar to that of mean().

In [75]:
# Computing mean
np.mean(samples)

5.026573203193191

In [76]:
np.average(samples)

5.026573203193191

In [77]:
# Computing mean with axis=1 (over each row)
np.mean(samples_2d, axis=1)

array([4.52183002, 5.56338579, 5.61101951, 5.17978692, 4.41731783])

In [78]:
np.average(samples_2d, axis=1)

array([4.52183002, 5.56338579, 5.61101951, 5.17978692, 4.41731783])

In [79]:
# max(a, axis=None) returns the maximum of an array or maximum along an axis.
np.max(samples)

9.789146553453758

In [80]:
np.max(samples_2d, axis=1)

array([5.25763422, 6.79706788, 7.14757576, 6.31779307, 6.264378  ])

In [81]:
# median(a, axis=None) returns the median along the specified axis.
np.median(samples)

5.098069026250922

In [82]:
np.median(samples_2d)

5.179678353216241

In [83]:
# min(a, axis=None) returns the minimum of an array or minimum along an axis.
np.min(samples)

-0.27226949047607185

In [84]:
np.min(samples_2d, axis=1)

array([3.34475665, 4.80735688, 3.84824416, 3.74420049, 1.85255307])

In [85]:
# var(a, axis=None) returns the variance of an array or along the specified axis.
np.var(samples)

2.3327063390387055

In [86]:
np.var(samples_2d)

1.3855850424926859

In [87]:
# The variance is computed over each column of numbers
np.var(samples_2d, axis=0)

array([0.49665574, 0.86958212, 0.95661624, 0.92631087, 2.91767263])

In [88]:
# std(a, axis=None) returns the standard deviation of an array or along the specified axis.
np.std(samples)

1.5273199858047775

In [89]:
np.std(samples_2d)

1.1771087640879605

In [90]:
# sum(a, axis=None) returns the sum of array elements.
# Recalling the array n_put_vol

n_put_vol

array([52.89, 45.14, 63.84, 77.1 , 74.6 ])

In [91]:
# Computing sum of all elements within n_put_vol
np.sum(n_put_vol)

313.57

In [92]:
# Computing sum of all array over each row
np.sum(samples_2d, axis=1)

array([22.60915011, 27.81692893, 28.05509755, 25.89893461, 22.08658916])

In [93]:
# cumsum(a, axis=None) returns the cumulative sum of the elements along a given axis.
np.cumsum(n_put_vol)

array([ 52.89,  98.03, 161.87, 238.97, 313.57])

In [94]:
# Using np. format to compute the sum
np.sum(samples)

5026.573203193191

In [95]:
# Calling sum() directly on a NumPy object
samples.sum()

5026.573203193191

### Array Manipulation

In [96]:
a = np.array([1, 2, 3])

In [97]:
b = np.array([3, 3, 3])

In [98]:
a * b

array([3, 6, 9])

In [99]:
a = np.array([1, 2, 3])

In [101]:
b = 3

In [102]:
a * b

array([3, 6, 9])

In [103]:
# exp(*args) returns the exponential of all elements in the input array.
# The numbers will be raised to e also known as Euler’s number.
# Computing exponentials for the array 'a'

np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [104]:
# sqrt(*args) returns the positive square-root of an array, elementwise.
# Computing square roots of a given array

np.sqrt([1, 4, 9, 16, 25])

array([1., 2., 3., 4., 5.])

In [105]:
# reshape(new_shape) gives a new shape to an array without changing its data.
# Creating a one-dimensional array with 12 elements

res = np.arange(12)

In [106]:
res

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
# Reshaping the 'res' array to 2-dimensional array
np.reshape(res, (3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
# Reshaping the dimensions from (3, 4) to (2, 6)
np.reshape(res, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [109]:
# resize(a, new_shape) return a new array with the specified shape.
# If the new array is larger than the original array, then the new array is filled with repeated copies of a.
# Creating a one-dimensional array

demo = np.arange(4)

In [110]:
demo

array([0, 1, 2, 3])

In [111]:
# Resizing a 'demo' array to (2, 2)
np.resize(demo, (2, 2))

array([[0, 1],
       [2, 3]])

In [112]:
# Resizing a 'demo' greater than its size.
np.resize(demo, (4, 2))

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [113]:
# round(a, decimals=0) round an array to the given number of decimals.
# If decimals are not given, elements will be rounded to the whole number.

In [114]:
# Creating a one-dimensional array
a = np.random.rand(5)

In [115]:
# Printing array
a

array([0.63174183, 0.0272961 , 0.62655895, 0.64727765, 0.6066466 ])

In [116]:
# Rounding to 0 decimals
a.round()

array([1., 0., 1., 1., 1.])

In [117]:
# Rounding to 0 decimals using the np.round syntax
np.round(a)

array([1., 0., 1., 1., 1.])

In [118]:
# Rounding to 2 decimals
a.round(2)

array([0.63, 0.03, 0.63, 0.65, 0.61])

In [119]:
# Rounding to 3 decimals using the np.round syntax
np.round(a, 3)

array([0.632, 0.027, 0.627, 0.647, 0.607])

In [120]:
# sort(a, kind='quicksort') returns a sorted copy of an array. The
# default sorting algorithm used is quicksort. Other available options
# are mergesort and heapsort.

np.sort(n_put_vol)

array([45.14, 52.89, 63.84, 74.6 , 77.1 ])

In [121]:
np.sort(samples_2d)

array([[3.34475665, 4.36730802, 4.56565369, 5.07379752, 5.25763422],
       [4.80735688, 5.17967835, 5.41236199, 5.62046383, 6.79706788],
       [3.84824416, 4.71425406, 5.95932065, 6.38570291, 7.14757576],
       [3.74420049, 5.05359946, 5.24699917, 5.53634242, 6.31779307],
       [1.85255307, 3.63557548, 4.29446805, 6.03961456, 6.264378  ]])

In [122]:
# vstack(tup) stacks arrays provided via tup in sequence vertically (row wise).

In [123]:
# hstack(tup) stacks arrays provided via tup in sequence horizontally (column wise).

In [124]:
# column_stack(tup) stacks 1-dimensional arrays as column into a 2-
# dimensional array. It takes a sequence of 1-D arrays and stacks them
# as columns to make a single 2-D array.

# Creating sample arrays
a = np.array([1, 2, 3])

In [125]:
b = np.array([4, 5, 6])

In [126]:
c = np.array([7, 8, 9])

In [127]:
# Stacking arrays vertically
np.vstack((a, b, c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
# Stacking arrays horizontally
np.hstack((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
# Stacking two arrays together
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [130]:
# Stacking three arrays together
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [131]:
# transpose() permutes the dimensions of an array.
# Creating a two-dimensional array with shape (2, 4)
a = np.arange(8).reshape(2, 4)

In [132]:
# Printing it
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [133]:
# Transposing the array
a.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

### Array Indexing and Iterating

#### Indexing and Subsetting

In [134]:
# Creating one-dimensional array
arr_1d = np.array([52, 88, 41, 63, 94])

In [135]:
# Creating two-dimensional array
arr_2d = np.array([['a', 'b', 'c'],
                   ['d', 'e', 'f'],
                   ['g', 'h', 'i']])

In [136]:
# Slicing the element at index 0
arr_1d[0]

52

In [137]:
# Slicing the last element using negative index
arr_1d[-1]

94

In [138]:
# Slicing elements from position 2 (inclusive) to
# 5 (exclusive)
arr_1d[2:5]

array([41, 63, 94])

In [139]:
# Slicing the element at position (0, 1)
arr_2d[0, 1]

'b'

In [140]:
# Slicing the element at position (1, 2)
arr_2d[1, 2]

'f'

In [141]:
# Slicing the element at position (2, 0)
arr_2d[2, 0]

'g'

In [142]:
# Slicing the first row
arr_2d[0, ]

array(['a', 'b', 'c'], dtype='<U1')

In [143]:
# Slicing the last column
arr_2d[:, 2]

array(['c', 'f', 'i'], dtype='<U1')

In [144]:
arr_2d[:]

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

#### Boolean Indexing

In [145]:
# Creating an array
arr = np.arange(1, 10)

In [146]:
# Printing the array
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
# Subsetting the array `arr` using an anonymous array
arr[np.array([2, 5, 5, 1])]

array([3, 6, 6, 2])

In [148]:
# Creating an random array with 20 values
rand_arr = np.random.randint(1, 50, 20)

In [149]:
# Printing the array
rand_arr

array([27, 19,  6, 19,  8, 46, 29, 12, 36, 39, 17,  6, 46, 42, 18, 21, 21,
        6, 33, 40])

In [150]:
# Filtering the array values which are greater than 30
rand_arr[rand_arr > 30]

array([46, 36, 39, 46, 42, 33, 40])

In [151]:
filter_ = rand_arr > 30

In [152]:
filter_

array([False, False, False, False, False,  True, False, False,  True,
        True, False, False,  True,  True, False, False, False, False,
        True,  True])

In [153]:
# Filtering an array using np.where method
rand_arr[np.where(rand_arr > 30)]

array([46, 36, 39, 46, 42, 33, 40])

In [ ]:
np.where[condition[, x, y]]

In [155]:
# Creating an array heights
heights = np.random.uniform(150, 160, size=20)

In [156]:
heights

array([150.89739234, 156.46506073, 153.92706465, 157.67523425,
       157.63181804, 152.2135747 , 153.38177257, 156.48486304,
       158.63159531, 159.59359052, 152.48543803, 155.11632073,
       158.88169701, 155.63546245, 157.56343127, 151.77832019,
       150.91492258, 158.10788453, 153.277323  , 154.2750867 ])

In [157]:
np.where(heights > 153)

(array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14, 17, 18, 19],
       dtype=int64),)

In [158]:
np.where(heights > 153, True, False)

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False,  True,
        True,  True])

In [159]:
# Creating an array 'x_array'
x_array = np.arange(11, 31, 1)

In [160]:
x_array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [161]:
# Creating an array 'y_array'
y_array = np.arange(111, 131, 1)

In [162]:
y_array

array([111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124, 125, 126, 127, 128, 129, 130])

In [163]:
np.where(heights > 153, x_array, y_array)

array([111,  12,  13,  14,  15, 116,  17,  18,  19,  20, 121,  22,  23,
        24,  25, 126, 127,  28,  29,  30])

In [164]:
# Hypothetical close prices for 20 periods
close_price = np.random.randint(132, 140, 20)

In [165]:
# Printing close_price
close_price

array([132, 136, 132, 135, 136, 136, 134, 135, 137, 136, 136, 137, 133,
       136, 134, 134, 138, 137, 137, 136])

In [166]:
# Average close price
avg_price = 135.45

In [167]:
# Computing trading signals with 1 being 'buy' and 0
# represents 'no signal'

signals = np.where(close_price > avg_price, 1, 0)

In [169]:
# Printing signals
signals

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1])

#### Iterating Over Arrays

In [170]:
# Looping over a one-dimensional array
for element in arr_1d:
    print(element)

52
88
41
63
94


In [171]:
for element in arr_2d:
    print(element)

['a' 'b' 'c']
['d' 'e' 'f']
['g' 'h' 'i']


In [172]:
for element in arr_2d:
    for e in element:
        print(e)

a
b
c
d
e
f
g
h
i


In [173]:
for element in np.nditer(arr_2d):
    print(element)

a
b
c
d
e
f
g
h
i


In [174]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.